apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      securityContext:
        fsGroup: 65534
      serviceAccountName: prometheus  
      containers:
        - name: prometheus
          image: prom/prometheus
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
          resources: 
            limits: 
              cpu: 500m
              memory: 800Mi
            requests: 
              cpu: 100m
              memory: 200Mi       
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf


---
apiVersion: v1
kind: Service
metadata:
  name: promethesus-svc
  namespace: monitoring
spec:
  selector:
    app: prometheus-server
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
  type: NodePort
