apiVersion: v1
kind: ConfigMap
metadata:
  name: apacheconfig
  namespace: myconf
  labels:
    app: confserver
data:
  default.conf: |
    <VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ErrorLog /var/log/httpd/error.log
        CustomLog /var/log/httpd/access.log combined
    </VirtualHost>  
    <Directory /var/www/html>
        Require all granted 
    </Directory>    

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webconfig
  namespace: myconf
  labels:
    app: confserver
data:
  web.conf: |
    <VirtualHost *:8080>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/web
        ErrorLog /var/log/httpd/error.log
        CustomLog /var/log/httpd/access.log combined
    </VirtualHost>  
    <Directory /var/www/web>
        Require all granted 
    </Directory>
