apiVersion: v1
kind: ConfigMap
metadata:
  name: apacheconfig
  namespace: myconf
  labels:
    app: confserver
data:
  default.conf: |
    <VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>  
    <documentroot /var/www/html>
        Require all granted 
    </documetroot>    

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webconfig
  namespace: myconf
  labels:
    app: confserver
data:
  web.conf: |
    <VirtualHost *:8080>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>  
    <documentroot /var/www/html>
        Require all granted 
    </documetroot>
