apiVersion: v1
kind: Namespace
metadata:
  name: myconf 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confserver
  namespace: myconf
spec:
  selector:
    matchLabels:
      app: confserver
  template:
    metadata:
      labels:
        app: confserver
    spec:
      volumes:
      - name: apache-defaultconfig-volume
        configMap:
          name: apacheconfig
      - name: apache-webconfig-volume
        configMap:
          name: webconfig 
      - name: html-volume
        host_path: 
          path: /mnt/html/
          type: Directory
      - name: web-html-volume
        host_path:
          path: /mnt/web/
          type: Directory

      containers:
      - name: confserver
        image: prateekkumawat/niteshapp:webserver
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 82
          name: http
        - containerPort: 80
          name: defaulthttp
        - containerPort: 8080
          name: app-http
        command:
          - sleep
          - "3600"
        volumeMounts: 
        - name: apache-defaultconfig-volume
          mountPath: /etc/httpd/conf.d/default.conf
          subPath: default.conf
        - name: apache-webconfig-volume
          mountPath: /etc/httpd/conf.d/web.conf 
          subPath: web.conf  
        - name: html-volume
          mountPath: /var/www/html
        - name: web-html-volume
          mountPath: /var/www/web
---
apiVersion: v1
kind: Service
metadata:
  name: confserver-service
  namespace: myconf
spec:
  selector:
    app: confserer
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 82
    targetPort: 82  
    name: defaulthttp
  - port: 8080
    targetPort: 8080
    name: app-http  

