apiVersion: v1
kind: Pod
metadata:
  name: pg-client
  namespace: postgres
spec:
  containers:
  - name: postgres-debugpod
    image: postgres:18-alpine3.23
    env:
      - name: PGHOST
        value: postgres-database-svc.postgres.svc.cluster.local
      - name: PGUSER
        value: "postgres"
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef: 
              name: postgres-secret
              key: password
      - name: PGDATABASE
        value: testdata
    resources: 
      requests:
        cpu: "100m" 
        memory: "100Mi"   
      limits:
        cpu: "150m" 
        memory: "200Mi"     
    command: ["sleep", "3600"]
  restartPolicy: Never