apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app.kubernetes.io/name: webapp
spec:
  containers:
  - name: webapp
    image: prateekkumawat/niteshclass:webapp1
    resources:
      requests:
        memory: "200Mi"
        cpu: "150m"
      limits:
        memory: "400Mi"
        cpu: "300m"
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  selector:
     app.kubernetes.io/name: webapp
  type: NodePort   
  ports:
  - port: 82
    targetPort: 80

