apiVersion: v1
kind: Namespace
metadata:
  name: database

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: database
type: Opaque
data:
  password: UmVkaGF0MTIzNDU2
  username: aHNpdGFkbWlu   

--- 
apiVersion: v1
kind: Secret
metadata:
  name: database-admin-secret
  namespace: database
type: Opaque
data:
  password: YWRtaW5wYXNzMTIz

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
spec:
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql-app
        image: mysql:latest
        resources:
          requests:
            memory: "300Mi"
            cpu: "500m"
          limits:
            memory: "800Mi"
            cpu: "700m"
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: database-admin-secret
              key: password    
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: MYSQL_DATABASE
          value: testdb

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: database
spec:
  selector:
    app: mysql-app
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql 


